//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiFestRock.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdEventosEntities : DbContext
    {
        public bdEventosEntities()
            : base("name=bdEventosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblArtista> tblArtistas { get; set; }
        public virtual DbSet<tblBanda> tblBandas { get; set; }
        public virtual DbSet<tblBandaArt> tblBandaArts { get; set; }
        public virtual DbSet<tblCiudad> tblCiudads { get; set; }
        public virtual DbSet<tblDetInsc> tblDetInscs { get; set; }
        public virtual DbSet<tblDpto> tblDptoes { get; set; }
        public virtual DbSet<tblEvento> tblEventoes { get; set; }
        public virtual DbSet<tblGenero> tblGeneroes { get; set; }
        public virtual DbSet<tblInscrip> tblInscrips { get; set; }
        public virtual DbSet<tblInstrum> tblInstrums { get; set; }
        public virtual DbSet<tblTipoDoc> tblTipoDocs { get; set; }
    }
}
