//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiFestRock.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblArtista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArtista()
        {
            this.tblBandaArts = new HashSet<tblBandaArt>();
        }
    
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public int idtipoDoc { get; set; }
        public int nroDoc { get; set; }
        public int idGenero { get; set; }
        public int idCiudad { get; set; }

        [JsonIgnore]
        public virtual tblCiudad tblCiudad { get; set; }
        [JsonIgnore]
        public virtual tblGenero tblGenero { get; set; }
        [JsonIgnore]
        public virtual tblTipoDoc tblTipoDoc { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBandaArt> tblBandaArts { get; set; }
    }
}
