//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiFestRock.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblBandaArt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBandaArt()
        {
            this.tblDetInscs = new HashSet<tblDetInsc>();
        }
    
        public int Codigo { get; set; }
        public int idBanda { get; set; }
        public int idArtista { get; set; }
        public int idInstrum { get; set; }
        public bool Activo { get; set; }

        [JsonIgnore]
        public virtual tblArtista tblArtista { get; set; }
        [JsonIgnore]
        public virtual tblBanda tblBanda { get; set; }
        [JsonIgnore]
        public virtual tblInstrum tblInstrum { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetInsc> tblDetInscs { get; set; }
    }
}
