//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiFestRock.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class tblBanda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBanda()
        {
            this.tblBandaArts = new HashSet<tblBandaArt>();
            this.tblInscrips = new HashSet<tblInscrip>();
        }

        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public int AnioFund { get; set; }
        public int idCiudad { get; set; }
        public bool Activo { get; set; }

        [JsonIgnore]
        public virtual tblCiudad tblCiudad { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
        public virtual ICollection<tblBandaArt> tblBandaArts { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<tblInscrip> tblInscrips { get; set; }
    }
}
