//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiFestRock.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetInsc
    {
        public int Codigo { get; set; }
        public int idNroInsc { get; set; }
        public int idBandArt { get; set; }
        public int Edad { get; set; }

        [JsonIgnore]
        public virtual tblBandaArt tblBandaArt { get; set; }
        [JsonIgnore]
        public virtual tblInscrip tblInscrip { get; set; }
    }
}
