//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiFestRock.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvento()
        {
            this.tblInscrips = new HashSet<tblInscrip>();
        }
    
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public int idCiudad { get; set; }
        public int Anio { get; set; }
        public string Fecha { get; set; }
        public string Lugar { get; set; }

        [JsonIgnore]
        public virtual tblCiudad tblCiudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<tblInscrip> tblInscrips { get; set; }
    }
}
