//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiFestRock.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblInscrip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInscrip()
        {
            this.tblDetInscs = new HashSet<tblDetInsc>();
        }
    
        public int Codigo { get; set; }
        public int idEvento { get; set; }
        public int idBanda { get; set; }
        public string Represenante { get; set; }
        public string Telefono { get; set; }
        public int valor { get; set; }

        [JsonIgnore]
        public virtual tblBanda tblBanda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<tblDetInsc> tblDetInscs { get; set; }
        [JsonIgnore]
        public virtual tblEvento tblEvento { get; set; }
    }
}
